import React, { useEffect, useState } from 'react';
import { Calendar, Video, Clock, CheckCircle, XCircle, User, Bot } from 'lucide-react';
import { getMeetings } from '../services/api';
import { Meeting } from '../types';

const Meetings: React.FC = () => {
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'upcoming' | 'past'>('upcoming');

  useEffect(() => {
    getMeetings().then(data => {
        setMeetings(data);
        setLoading(false);
    });
  }, []);

  const displayedMeetings = activeTab === 'upcoming' 
    ? meetings.filter(m => !m.date || new Date(m.date) >= new Date()) 
    : meetings.filter(m => m.date && new Date(m.date) < new Date());

  // Sorting
  displayedMeetings.sort((a, b) => new Date(a.date || '2099-01-01').getTime() - new Date(b.date || '2099-01-01').getTime());
  if (activeTab === 'past') displayedMeetings.reverse();

  if (loading) return <div className="p-12 text-center text-gray-400">Loading schedule...</div>;

  return (
    <div className="space-y-6 animate-fade-in">
        <div className="flex justify-between items-end">
            <div>
                <h2 className="text-2xl font-bold text-gray-900">Revenue Moments</h2>
                <p className="text-gray-500 text-sm">Meetings generated by your AI workforce.</p>
            </div>
            <div className="bg-gray-100 p-1 rounded-lg flex gap-1">
                {['upcoming', 'past'].map((tab) => (
                    <button 
                        key={tab}
                        onClick={() => setActiveTab(tab as any)}
                        className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all capitalize ${activeTab === tab ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        {tab}
                    </button>
                ))}
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <KPI icon={Calendar} label="Total Booked" value={meetings.length} color="bg-green-100 text-green-600" />
            <KPI icon={Bot} label="AI Generated" value={meetings.filter(m => m.isAiBooked).length} sub={`${Math.round((meetings.filter(m => m.isAiBooked).length/meetings.length)*100) || 0}%`} color="bg-purple-100 text-purple-600" />
            <KPI icon={Video} label="Show-Up Rate" value="87%" sub="+2% vs last mo" color="bg-blue-100 text-blue-600" />
        </div>

        <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
            <div className="p-4 bg-gray-50 border-b border-gray-200">
                <h3 className="font-bold text-gray-900 text-sm uppercase tracking-wide">{activeTab} Schedule</h3>
            </div>
            {displayedMeetings.length === 0 ? (
                <div className="p-12 text-center text-gray-500 flex flex-col items-center">
                    <Calendar size={48} className="mb-4 opacity-20" />
                    <p>No {activeTab} meetings found in records.</p>
                </div>
            ) : (
                <div className="divide-y divide-gray-100">
                    {displayedMeetings.map((meeting) => (
                        <div key={meeting.id} className="p-6 hover:bg-gray-50 transition-colors flex flex-col md:flex-row md:items-center justify-between gap-4">
                            <div className="flex items-start gap-4">
                                <div className="flex flex-col items-center justify-center w-14 h-14 bg-blue-50 text-blue-700 rounded-xl border border-blue-100 shadow-sm">
                                    <span className="text-xs font-bold uppercase">{meeting.date ? new Date(meeting.date).toLocaleString('default', { month: 'short' }) : 'TBD'}</span>
                                    <span className="text-xl font-bold">{meeting.date ? new Date(meeting.date).getDate() : '?'}</span>
                                </div>
                                <div>
                                    <h4 className="font-bold text-gray-900 text-lg">{meeting.leadName}</h4>
                                    <div className="flex items-center gap-2 text-sm text-gray-500 mt-1">
                                        <Clock size={14} />
                                        {meeting.time}
                                        <span className="mx-1">•</span>
                                        <Video size={14} />
                                        {meeting.platform || 'Google Meet'}
                                    </div>
                                    <div className="flex items-center gap-2 mt-2">
                                        {meeting.isAiBooked && (
                                            <span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded border bg-purple-50 text-purple-700 border-purple-200">
                                                <Bot size={10} /> Booked by AI Agent
                                            </span>
                                        )}
                                        {!meeting.isAiBooked && (
                                            <span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded border bg-gray-100 text-gray-600 border-gray-200">
                                                <User size={10} /> Manual Booking
                                            </span>
                                        )}
                                    </div>
                                </div>
                            </div>
                            <div className="flex items-center gap-3">
                                {activeTab === 'upcoming' && meeting.link && (
                                    <a 
                                        href={meeting.link} 
                                        target="_blank" 
                                        rel="noreferrer"
                                        className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors shadow-sm"
                                    >
                                        Join Meeting
                                    </a>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    </div>
  );
};

const KPI = ({ icon: Icon, label, value, sub, color }: any) => (
    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-center gap-4">
        <div className={`p-3 rounded-lg ${color}`}>
            <Icon size={24} />
        </div>
        <div>
            <p className="text-sm text-gray-500">{label}</p>
            <div className="flex items-baseline gap-2">
                <p className="text-2xl font-bold text-gray-900">{value}</p>
                {sub && <span className="text-xs text-green-600 font-medium">{sub}</span>}
            </div>
        </div>
    </div>
);

export default Meetings;