import React, { useEffect, useState } from 'react';
import { Calendar, Video, Clock, CheckCircle, XCircle, User, Bot, ExternalLink, X, Sparkles, FileText, MapPin, Link as LinkIcon, AlertTriangle } from 'lucide-react';
import { getMeetings, getLeads } from '../services/api';
import { Meeting, UnifiedLead } from '../types';
import { SHEET_IDS } from '../constants';
import DOMPurify from 'dompurify';

const Meetings: React.FC = () => {
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [leads, setLeads] = useState<UnifiedLead[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'upcoming' | 'past'>('upcoming');
  const [selectedLead, setSelectedLead] = useState<UnifiedLead | null>(null);

  useEffect(() => {
    const fetchData = async () => {
        const [meetingsData, leadsData] = await Promise.all([
            getMeetings(),
            getLeads()
        ]);
        setMeetings(meetingsData);
        setLeads(leadsData);
        setLoading(false);
    };
    fetchData();
  }, []);

  const displayedMeetings = activeTab === 'upcoming' 
    ? meetings.filter(m => !m.date || new Date(m.date) >= new Date()) 
    : meetings.filter(m => m.date && new Date(m.date) < new Date());

  displayedMeetings.sort((a, b) => new Date(a.date || '2099-01-01').getTime() - new Date(b.date || '2099-01-01').getTime());
  if (activeTab === 'past') displayedMeetings.reverse();

  const handleLeadClick = (email: string) => {
      const lead = leads.find(l => l.email.toLowerCase() === email.toLowerCase());
      if (lead) {
          setSelectedLead(lead);
      } else {
          alert("Detailed lead profile not found in Master Sheet.");
      }
  };

  const getPlatformIcon = (platform: string) => {
      const p = platform.toLowerCase();
      if (p.includes('zoom')) return <Video size={14} className="text-blue-500" />;
      if (p.includes('google') || p.includes('meet')) return <Video size={14} className="text-green-500" />;
      return <Video size={14} className="text-gray-500" />;
  };

  if (loading) return <div className="p-12 text-center text-gray-400">Loading schedule & intelligence...</div>;

  return (
    <div className="space-y-6 animate-fade-in relative">
        <div className="flex justify-between items-end">
            <div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Revenue Moments</h2>
                <p className="text-gray-500 dark:text-gray-400 text-sm">Meetings generated by your AI workforce.</p>
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 p-1 rounded-lg flex gap-1">
                {['upcoming', 'past'].map((tab) => (
                    <button 
                        key={tab}
                        onClick={() => setActiveTab(tab as any)}
                        className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all capitalize ${activeTab === tab ? 'bg-white dark:bg-gray-700 shadow text-gray-900 dark:text-white' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300'}`}
                    >
                        {tab}
                    </button>
                ))}
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <KPI icon={Calendar} label="Total Booked" value={meetings.length} color="bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400" />
            <KPI icon={Bot} label="AI Generated" value={meetings.filter(m => m.isAiBooked).length} sub={`${Math.round((meetings.filter(m => m.isAiBooked).length/meetings.length)*100) || 0}%`} color="bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400" />
            <KPI icon={Video} label="Show-Up Rate" value="87%" sub="+2% vs last mo" color="bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400" />
        </div>

        <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl shadow-sm overflow-hidden">
            <div className="p-4 bg-gray-50 dark:bg-gray-750 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
                <h3 className="font-bold text-gray-900 dark:text-white text-sm uppercase tracking-wide">{activeTab} Schedule</h3>
                <span className="text-xs text-gray-500 dark:text-gray-400">{displayedMeetings.length} meetings</span>
            </div>
            {displayedMeetings.length === 0 ? (
                <div className="p-12 text-center text-gray-500 dark:text-gray-400 flex flex-col items-center">
                    <Calendar size={48} className="mb-4 opacity-20" />
                    <p>No {activeTab} meetings found in records.</p>
                </div>
            ) : (
                <div className="divide-y divide-gray-100 dark:divide-gray-700">
                    {displayedMeetings.map((meeting) => (
                        <div key={meeting.id} className="p-6 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors flex flex-col md:flex-row md:items-center justify-between gap-6 group">
                            
                            {/* Date Badge */}
                            <div className="flex items-start gap-4 flex-1">
                                <div className="flex flex-col items-center justify-center w-16 h-16 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-xl border border-gray-200 dark:border-gray-600 shadow-sm group-hover:border-blue-300 dark:group-hover:border-blue-500 transition-colors">
                                    <span className="text-xs font-bold uppercase text-gray-500 dark:text-gray-400">{meeting.date ? new Date(meeting.date).toLocaleString('default', { month: 'short' }) : 'TBD'}</span>
                                    <span className="text-2xl font-bold">{meeting.date ? new Date(meeting.date).getDate() : '?'}</span>
                                </div>
                                
                                {/* Meeting Context */}
                                <div>
                                    <h4 
                                        onClick={() => handleLeadClick(meeting.email)}
                                        className="font-bold text-gray-900 dark:text-white text-lg hover:text-blue-600 dark:hover:text-blue-400 cursor-pointer flex items-center gap-2"
                                    >
                                        {meeting.leadName}
                                        <ExternalLink size={14} className="opacity-0 group-hover:opacity-100 text-blue-400 transition-opacity" />
                                    </h4>
                                    
                                    <div className="flex items-center gap-3 text-sm text-gray-500 dark:text-gray-400 mt-1">
                                        <div className="flex items-center gap-1.5">
                                            <Clock size={14} />
                                            <span className="font-medium text-gray-700 dark:text-gray-300">{meeting.time}</span>
                                        </div>
                                        <span className="text-gray-300 dark:text-gray-600">|</span>
                                        <div className="flex items-center gap-1.5">
                                            {getPlatformIcon(meeting.platform)}
                                            <span>{meeting.platform || 'Virtual Meeting'}</span>
                                        </div>
                                    </div>

                                    <div className="flex items-center gap-2 mt-2">
                                        {meeting.isAiBooked ? (
                                            <span className="inline-flex items-center gap-1 text-[10px] uppercase font-bold px-2 py-0.5 rounded bg-purple-50 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 border border-purple-100 dark:border-purple-800">
                                                <Bot size={10} /> AI Appointment Setter
                                            </span>
                                        ) : (
                                            <span className="inline-flex items-center gap-1 text-[10px] uppercase font-bold px-2 py-0.5 rounded bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 border border-gray-200 dark:border-gray-600">
                                                <User size={10} /> {meeting.bookedBy || 'Manual'}
                                            </span>
                                        )}
                                        <span className="text-[10px] text-gray-400 px-2">{meeting.email}</span>
                                    </div>
                                </div>
                            </div>

                            {/* Actions */}
                            <div className="flex items-center gap-3">
                                {activeTab === 'upcoming' && meeting.link ? (
                                    <a 
                                        href={meeting.link} 
                                        target="_blank" 
                                        rel="noreferrer"
                                        className="px-5 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-bold hover:bg-blue-700 transition-colors shadow-sm flex items-center gap-2"
                                    >
                                        <Video size={16} />
                                        Join Meeting
                                    </a>
                                ) : (
                                    <span className="text-sm text-gray-400 italic px-4">
                                        {activeTab === 'past' ? 'Completed' : 'No Link'}
                                    </span>
                                )}
                                <button 
                                    onClick={() => handleLeadClick(meeting.email)}
                                    className="p-2.5 text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg border border-transparent hover:border-gray-200 dark:hover:border-gray-600 transition-all"
                                    title="View Analysis"
                                >
                                    <FileText size={18} />
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>

        {/* Lead Analysis Drawer */}
        {selectedLead && (
            <div className="fixed inset-0 z-50 flex justify-end">
                <div className="absolute inset-0 bg-black/30 backdrop-blur-sm transition-opacity" onClick={() => setSelectedLead(null)}></div>
                <div className="relative w-full max-w-2xl bg-white dark:bg-gray-900 h-full shadow-2xl flex flex-col animate-slide-in-right transform transition-transform">
                    {/* Drawer Header */}
                    <div className="p-6 border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 flex justify-between items-start">
                        <div className="flex gap-4">
                            <div className="w-14 h-14 rounded-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 flex items-center justify-center text-xl font-bold text-gray-700 dark:text-gray-200 shadow-sm">
                                {selectedLead.firstName[0]}{selectedLead.lastName[0]}
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 dark:text-white">{selectedLead.firstName} {selectedLead.lastName}</h3>
                                <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300 mt-0.5">
                                    <span>{selectedLead.jobTitle}</span>
                                    <span className="text-gray-300 dark:text-gray-600">•</span>
                                    <span className="font-medium text-gray-900 dark:text-white">{selectedLead.company}</span>
                                </div>
                                <div className="flex gap-2 mt-3">
                                    <span className="text-xs px-2 py-1 bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded text-gray-600 dark:text-gray-300 flex items-center gap-1">
                                        <MapPin size={10} /> {selectedLead.country}
                                    </span>
                                    <a 
                                        href={`https://docs.google.com/spreadsheets/d/${SHEET_IDS.LEAD_GEN}/edit`}
                                        target="_blank"
                                        rel="noreferrer"
                                        className="text-xs px-2 py-1 bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-800 text-green-700 dark:text-green-400 rounded hover:bg-green-100 dark:hover:bg-green-900/50 flex items-center gap-1 transition-colors"
                                    >
                                        <ExternalLink size={10} /> Lead Gen Sheet
                                    </a>
                                </div>
                            </div>
                        </div>
                        <button onClick={() => setSelectedLead(null)} className="p-1 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-full transition-colors">
                            <X size={24} />
                        </button>
                    </div>
                    
                    {/* Drawer Content */}
                    <div className="flex-1 overflow-y-auto p-6 space-y-8">
                         {/* Meeting Prep Alert */}
                         <div className="bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-100 dark:border-indigo-800 rounded-xl p-4 flex gap-3">
                            <Sparkles className="text-indigo-600 dark:text-indigo-400 flex-shrink-0" size={20} />
                            <div>
                                <h4 className="font-bold text-indigo-900 dark:text-indigo-300 text-sm">Pre-Meeting AI Analysis</h4>
                                <p className="text-xs text-indigo-700 dark:text-indigo-400 mt-1">
                                    This lead was qualified by the AI Appointment Setter. Review the research report below to understand their business context and identified pain points before joining the call.
                                </p>
                            </div>
                         </div>

                        {/* Research Report */}
                        <section>
                            <h4 className="text-sm font-bold text-gray-900 dark:text-white uppercase tracking-wider mb-3 flex items-center gap-2">
                                <FileText size={14} className="text-blue-500" />
                                Research Report
                            </h4>
                            <div className="prose prose-sm prose-blue dark:prose-invert bg-white dark:bg-gray-800 p-5 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm text-gray-700 dark:text-gray-300 max-w-none">
                                {selectedLead.researchReport ? (
                                     <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(selectedLead.researchReport) }} />
                                ) : (
                                     <div className="text-center py-8 text-gray-400 italic flex flex-col items-center">
                                         <AlertTriangle size={24} className="mb-2 opacity-50" />
                                         <p>Research report pending generation.</p>
                                     </div>
                                )}
                            </div>
                        </section>
                        
                        {/* Engagement Stats */}
                        <section className="grid grid-cols-2 gap-4">
                            <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-100 dark:border-gray-700">
                                <h5 className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase mb-2">Campaign Activity</h5>
                                <div className="space-y-2">
                                    <div className="flex justify-between text-sm">
                                        <span className="text-gray-600 dark:text-gray-400">Emails Sent</span>
                                        <span className="font-bold text-gray-900 dark:text-white">{selectedLead.emailsSentCount}</span>
                                    </div>
                                    <div className="flex justify-between text-sm">
                                        <span className="text-gray-600 dark:text-gray-400">Opens</span>
                                        <span className="font-bold text-gray-900 dark:text-white">{selectedLead.emailsOpenedCount}</span>
                                    </div>
                                    <div className="flex justify-between text-sm">
                                        <span className="text-gray-600 dark:text-gray-400">Clicks</span>
                                        <span className="font-bold text-gray-900 dark:text-white">{selectedLead.emailsClickedCount}</span>
                                    </div>
                                </div>
                            </div>
                             <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-xl border border-gray-100 dark:border-gray-700">
                                <h5 className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase mb-2">Lead Score</h5>
                                <div className="flex items-center gap-3">
                                    <div className={`text-3xl font-bold ${selectedLead.score > 70 ? 'text-green-600 dark:text-green-400' : 'text-yellow-600 dark:text-yellow-400'}`}>
                                        {selectedLead.score}
                                    </div>
                                    <div className="text-xs text-gray-400">
                                        / 100 Points
                                    </div>
                                </div>
                                <div className="w-full bg-gray-200 dark:bg-gray-600 rounded-full h-1.5 mt-3">
                                    <div 
                                        className={`h-1.5 rounded-full ${selectedLead.score > 70 ? 'bg-green-500' : 'bg-yellow-500'}`} 
                                        style={{width: `${selectedLead.score}%`}}
                                    ></div>
                                </div>
                            </div>
                        </section>
                    </div>

                    {/* Footer Actions */}
                    <div className="p-4 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 flex justify-end gap-3">
                        <button 
                             onClick={() => window.open(`https://docs.google.com/spreadsheets/d/${SHEET_IDS.LEAD_GEN}/edit`, '_blank')}
                             className="px-4 py-2 border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 rounded-lg text-sm font-medium text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-600"
                        >
                            Open Raw Data
                        </button>
                        <button 
                            onClick={() => setSelectedLead(null)}
                            className="px-6 py-2 bg-gray-900 dark:bg-gray-700 text-white rounded-lg text-sm font-bold hover:bg-gray-800 dark:hover:bg-gray-600 shadow-sm"
                        >
                            Close Dossier
                        </button>
                    </div>
                </div>
            </div>
        )}
    </div>
  );
};

const KPI = ({ icon: Icon, label, value, sub, color }: any) => (
    <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm flex items-center gap-4">
        <div className={`p-3 rounded-lg ${color}`}>
            <Icon size={24} />
        </div>
        <div>
            <p className="text-sm text-gray-500 dark:text-gray-400">{label}</p>
            <div className="flex items-baseline gap-2">
                <p className="text-2xl font-bold text-gray-900 dark:text-white">{value}</p>
                {sub && <span className="text-xs text-green-600 dark:text-green-400 font-medium">{sub}</span>}
            </div>
        </div>
    </div>
);

export default Meetings;